import { currentBranch, parseRemote, pushBranch } from "./git.js";
import type { TicketIntelligence } from "./intelligence.js";
import { extractAcceptanceLines } from "./adf.js";

export type GitCredentials = {
  github_token?: string;
  gitlab_token?: string;
};

function buildMrBody(opts: {
  intelligence: TicketIntelligence;
  jira_base_url?: string;
}): string {
  const { intelligence } = opts;
  const key = intelligence.issue.key ?? "TICKET";
  const base = opts.jira_base_url?.replace(/\/+$/, "");
  const jiraLink = base ? `${base}/browse/${key}` : key;

  const acceptance = extractAcceptanceLines(intelligence.plain_description);
  const linked = Object.entries(intelligence.related_issues)
    .map(([k, v]) => {
      const summary = String(v.fields?.summary ?? "");
      const link = base ? `${base}/browse/${k}` : k;
      return `- [${k}](${link}): ${summary}`;
    })
    .join("\n");

  const descPreview = intelligence.plain_description
    .slice(0, 500)
    .split("\n")
    .slice(0, 5)
    .join("\n");

  const sections: string[] = [
    `## Jira: [${key}](${jiraLink})`,
    "",
    `**${intelligence.summary}**`,
    "",
    "## What changed",
    "_Fill in what was implemented — context from the ticket:_",
    descPreview || "_No description_",
    "",
    "## Acceptance criteria",
    acceptance.length
      ? acceptance.map((l) => `- [ ] ${l}`).join("\n")
      : "- [ ] Verify against ticket description",
    "",
  ];

  if (linked) {
    sections.push("## Linked issues", linked, "");
  }

  sections.push(
    "## Test plan",
    "- [ ] Acceptance criteria verified manually",
    "- [ ] Unit/integration tests updated",
    "- [ ] CI green",
    "",
    "_Generated by JiraFlow MCP_",
  );

  return sections.join("\n");
}

export async function createMergeRequest(opts: {
  repoRoot: string;
  intelligence: TicketIntelligence;
  parent_branch: string;
  creds: GitCredentials;
  jira_base_url?: string;
}): Promise<{ url: string; provider: string }> {
  const remote = await parseRemote(opts.repoRoot);
  if (!remote) {
    throw new Error("Could not parse origin remote for GitHub/GitLab.");
  }

  const branch = await currentBranch(opts.repoRoot);
  await pushBranch(opts.repoRoot, branch);

  const key = opts.intelligence.issue.key ?? "TICKET";
  const title = `${key}: ${opts.intelligence.summary}`;
  const body = buildMrBody({
    intelligence: opts.intelligence,
    jira_base_url: opts.jira_base_url,
  });

  if (remote.provider === "github") {
    const token = opts.creds.github_token;
    if (!token) throw new Error("GitHub token required (device setup or GITHUB_TOKEN env).");
    const res = await fetch(
      `https://api.github.com/repos/${remote.owner}/${remote.repo}/pulls`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          head: branch,
          base: opts.parent_branch,
          body,
        }),
      },
    );
    const text = await res.text();
    if (!res.ok) throw new Error(`GitHub PR failed ${res.status}: ${text}`);
    const data = JSON.parse(text) as { html_url: string };
    return { url: data.html_url, provider: "github" };
  }

  const token = opts.creds.gitlab_token;
  if (!token) throw new Error("GitLab token required (device setup or GITLAB_TOKEN env).");
  const projectPath = encodeURIComponent(`${remote.owner}/${remote.repo}`);
  const res = await fetch(
    `https://gitlab.com/api/v4/projects/${projectPath}/merge_requests`,
    {
      method: "POST",
      headers: {
        "PRIVATE-TOKEN": token,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        source_branch: branch,
        target_branch: opts.parent_branch,
        description: body,
      }),
    },
  );
  const text = await res.text();
  if (!res.ok) throw new Error(`GitLab MR failed ${res.status}: ${text}`);
  const data = JSON.parse(text) as { web_url: string };
  return { url: data.web_url, provider: "gitlab" };
}
